# Generated by Django 4.2.7 on 2023-12-13 08:40
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import app

class Migration(migrations.Migration):

    def create_initial_data(apps, schema_editor):
        Picture = apps.get_model('app', 'Picture')
        User = apps.get_model('app', 'User')
        picture = Picture.objects.create(Pid='p0000000')
        admin_user = User.objects.create(Uid='u0000000', Uname='Administrator', phone='00000000000', pwd='888888',
                                         Pid=picture)

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "Gid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(8)],
                    ),
                ),
                ("Gname", models.CharField(max_length=20, verbose_name="菜品组名")),
            ],
            options={
                "verbose_name": "菜品组",
                "verbose_name_plural": "菜品组",
                "db_table": "Group",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "Pid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(8)],
                    ),
                ),
                (
                    "path",
                    models.ImageField(
                        null=True,
                        storage=app.util.ImageStorage(),
                        upload_to="image/",
                        verbose_name="图片路径",
                    ),
                ),
            ],
            options={
                "verbose_name": "图片",
                "verbose_name_plural": "图片",
                "db_table": "Picture",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "Tid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(8)],
                    ),
                ),
                ("Tname", models.CharField(max_length=20, verbose_name="标签名")),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "db_table": "Tag",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "Uid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(8)],
                    ),
                ),
                ("Uname", models.CharField(max_length=20, verbose_name="用户名")),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MaxLengthValidator(11)],
                        verbose_name="用户手机",
                    ),
                ),
                ("pwd", models.CharField(max_length=20, verbose_name="用户密码")),
                (
                    "Pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.picture",
                        verbose_name="用户头像",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "Oid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(8)],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, max_digits=5, verbose_name="订单总价"
                    ),
                ),
                ("time", models.DateField(auto_now_add=True)),
                (
                    "Uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                        verbose_name="订单用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "Order",
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "Did",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(8)],
                    ),
                ),
                ("Dname", models.CharField(max_length=20, verbose_name="菜品名")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="菜品价格"
                    ),
                ),
                ("description", models.CharField(max_length=500, verbose_name="菜品描述")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="菜品评分"
                    ),
                ),
                (
                    "star",
                    models.DecimalField(
                        decimal_places=0, max_digits=5, verbose_name="菜品收藏量"
                    ),
                ),
                (
                    "remain",
                    models.DecimalField(
                        decimal_places=0, max_digits=5, verbose_name="菜品剩余"
                    ),
                ),
                (
                    "Gid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.group",
                        verbose_name="菜品菜品组",
                    ),
                ),
                (
                    "Pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.picture",
                        verbose_name="菜品图片",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜品",
                "verbose_name_plural": "菜品",
                "db_table": "Dish",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "Cid",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxLengthValidator(8)],
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="评论内容")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="评论评分"
                    ),
                ),
                (
                    "Did",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dish",
                        verbose_name="评论菜品",
                    ),
                ),
                (
                    "Uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "db_table": "Comment",
            },
        ),
        migrations.CreateModel(
            name="UserStarDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dish"
                    ),
                ),
                (
                    "Uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={
                "db_table": "UserStarDish",
                "unique_together": {("Uid", "Did")},
            },
        ),
        migrations.CreateModel(
            name="DishTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dish"
                    ),
                ),
                (
                    "Tid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.tag"
                    ),
                ),
            ],
            options={
                "db_table": "DishTag",
                "unique_together": {("Did", "Tid")},
            },
        ),
        migrations.CreateModel(
            name="DishOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.DecimalField(
                        decimal_places=0, max_digits=5, verbose_name="点菜数量"
                    ),
                ),
                (
                    "Did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dish"
                    ),
                ),
                (
                    "Oid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.order"
                    ),
                ),
            ],
            options={
                "db_table": "DishOrder",
                "unique_together": {("Oid", "Did")},
            },
        ),
        migrations.CreateModel(
            name="CommentPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.comment"
                    ),
                ),
                (
                    "Pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.picture"
                    ),
                ),
            ],
            options={
                "db_table": "CommentPicture",
                "unique_together": {("Cid", "Pid")},
            },
        ),
        migrations.RunPython(create_initial_data),
    ]
